name: Lint
description: Run golangci-lint
inputs:
  path:
    description: Path to lint
    required: true
  module:
    description: 'Path to go.mod for Go version detection'
    required: false
    default: 'go.mod'
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: ${{ inputs.module }}
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12.2
        args: ${{ inputs.path }}
